### ISSUE TITLE
git branch detection fatal message

### ISSUE THREAD

**Issue by darkfeline** [hiddenlotus/eshell-prompt-extras#12]
`epe-git-branch` fails if the command prints a fatal message https://github.com/hiddenlotus/eshell-prompt-extras/blob/master/eshell-prompt-extras.el#L223

~~~
~/library:D:fatal: Not a git repository (or any parent up to mount point /media/cryptstore)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).* λ 
~~~

Fix is easy: `git symbolic-ref HEAD --short 2>/dev/null || echo -n detached`

**Comment by darkfeline** [comment]
Ignore my previous suggested fix, we should instead fix the detection:

~~~ emacs-lisp
(defun epe-git-p ()
  "If you installed git and in a git project."
  (and (eshell-search-path "git")
       (let ((gitdir (shell-command-to-string "git rev-parse --show-toplevel 2>/dev/null")))
         (if (= 0 (length gitdir))
             nil
           gitdir))))
~~~

**Comment by hiddenlotus** [comment]
Hi. When does this error happen?

**Comment by darkfeline** [comment]
It happens if, for example, `/home/bob` has a `.git`, `/home/bob/files` is a mounted drive, and you are in `/home/bob/file`.  `epe-git-p` should be using git's repo detection and not rolling its own by looking for a `.git` file.
