### ISSUE TITLE
eshell/basename error

### ISSUE THREAD

**Issue by quimmeetpays** [hiddenlotus/eshell-prompt-extras#8]
First of all, thank you for your work.
Second, I have an issue with eshell-prompt-extras, it seems that `eshell/basename` is not defined. Am I missing something?

When byte compiling eshell-promt-extras.el (eshell-prompt-extras-20141214.723, emacs 24.4):
`
In end of data:
eshell-prompt-extras.el:301:1:Warning: the function 'eshell/basename' is not known to be defined.
`
and when starting emacs with --debug-init, it shows:
`Debugger entered--Lisp error: (void-function eshell/basename)`
and when I load the first python file I had trouble with the directory local variables:
`Directory-local variables error: (error "Cannot save customizations; init file was not fully loaded")`
If I does not customize the eshell promt, works like a charm.

Any ideas?

**Comment by hiddenlotus** [comment]
Hi.
Thanks for your issue. It is fixed, and please update this package later.

**Comment by quimmeetpays** [comment]
Thank you, man. Works like a charm!
